springdoc:
  swagger-ui:
    # Swagger UI 접속 경로 (기본: /swagger-ui/index.html)
    path: /swagger-ui.html

server:
  # 서버 포트 설정 (기본 8080)
  port: 8082

spring:
  datasource:
    # ===== [DB 접속 설정] =====
    # 개발용/운영용에 맞게 URL 수정
    url: jdbc:mysql://shop-db.c74828wmikhx.ap-northeast-2.rds.amazonaws.com:3306/users?useSSL=false&serverTimezone=UTC&characterEncoding=UTF-8
#    url: jdbc:mysql://localhost:3307/users?useSSL=false&serverTimezone=UTC&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: admin
    password: "PgEhzLRi4Pf0cVFG5BhX"

  jpa:
    hibernate:
      # 개발/테스트: update, 운영: validate 권장
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
        # default_schema: auth_schema  # 필요 시 활성화

app:
  cors:
    # 프론트엔드 허용 도메인 (환경변수 FRONTEND_ORIGIN 없으면 기본값 사용)
    allowed-origin: ${FRONTEND_ORIGIN:http://shop.nextcloudlab.com}

jwt:
  # JWT 서명 시크릿 키 (32자 이상!)
  # 운영 환경에서는 환경변수로 주입 권장
  secret: "ThisIsASecureJWTSecretKeyString_Min32Chars!"
  # 토큰 유효 시간 (밀리초 단위) → 예: 10시간
  expiration-ms: 36000000

logging:
  level:
    # Spring Security 디버그 로그 (JWT 인증 흐름 확인용, 개발용)
    # 운영 환경에서는 반드시 제거
    org.springframework.security: DEBUG
